import { NavbarItem } from "@/types/navbar";
import { v4 as uuid } from "uuid";

export const navbarData: NavbarItem[] = [
  {
    id: uuid(),
    title: "Services",
    isOpen: false,
    submenu: [
      {
        id: uuid(),
        title: "scanCV",
        href: "/cv-screening",
        external: false,
        isComingSoon: false,
        description: "scanCVDescription",
      },
      {
        id: uuid(),
        title: "test1",
        href: "/coming-soon",
        external: false,
        isComingSoon: true,
        description: "test1Description",
      },
      {
        id: uuid(),
        title: "interview",
        href: "/automatic-interview",
        external: false,
        isComingSoon: false,
        description: "interviewDescription",
      },
      {
        id: uuid(),
        title: "test2",
        href: "/coming-soon",
        external: false,
        isComingSoon: true,
        description: "test2Description",
      },
      {
        id: uuid(),
        title: "createJob",
        href: "/job-creation",
        external: false,
        isComingSoon: false,
        description: "createJobDescription",
      },
      {
        id: uuid(),
        title: "test3",
        href: "/coming-soon",
        external: false,
        isComingSoon: true,
        description: "test3Description",
      },
      {
        id: uuid(),
        title: "tracking",
        href: "/tracking-system",
        external: false,
        isComingSoon: false,
        description: "trackingDescription",
      },
      {
        id: uuid(),
        title: "test4",
        href: "/coming-soon",
        external: false,
        isComingSoon: true,
        description: "test4Description",
      },
      {
        id: uuid(),
        title: "collaboration",
        href: "/collaboration",
        external: false,
        isComingSoon: false,
        description: "collaborationDescription",
      },
      {
        id: uuid(),
        title: "test5",
        href: "/coming-soon",
        external: false,
        isComingSoon: true,
        description: "test5Description",
      },
    ],
  },
  {
    id: uuid(),
    isOpen: false,
    title: "About",
    href: "#about",
    external: false,
  },
  {
    id: uuid(),
    isOpen: false,
    title: "solutions",
    submenu: [
      {
        id: uuid(),
        title: "headHunters",
        href: "/head-hunters",
        external: false,
        isComingSoon: false,
        description: "headHuntersDescription",
      },
      {
        id: uuid(),
        title: "greyCollar",
        href: "/grey-collar",
        external: false,
        isComingSoon: false,
        description: "greyCollarDescription",
      },
      {
        id: uuid(),
        title: "whiteCollar",
        href: "/white-collar",
        external: false,
        isComingSoon: false,
        description: "whiteCollarDescription",
      },
      {
        id: uuid(),
        title: "startup",
        href: "/startup",
        external: false,
        isComingSoon: false,
        description: "startupDescription",
      },
      {
        id: uuid(),
        title: "university",
        href: "/university",
        external: false,
        isComingSoon: false,
        description: "universityDescription",
      },
      {
        id: uuid(),
        title: "officialDom",
        href: "/official-dom",
        external: false,
        isComingSoon: false,
        description: "officialDomDescription",
      },
      {
        id: uuid(),
        title: "business",
        href: "/business",
        external: false,
        isComingSoon: false,
        description: "businessDescription",
      },
      // {
      //   id: uuid(),
      //   title: "tracking",
      //   href: "/tracking-system",
      //   external: false,
      //   isComingSoon: false,
      //   description: "trackingDescription",
      // },
      // {
      //   id: uuid(),
      //   title: "test4",
      //   href: "/coming-soon",
      //   external: false,
      //   isComingSoon: true,
      //   description: "test4Description",
      // },
      // {
      //   id: uuid(),
      //   title: "collaboration",
      //   href: "/collaboration",
      //   external: false,
      //   isComingSoon: false,
      //   description: "collaborationDescription",
      // },
      // {
      //   id: uuid(),
      //   title: "test5",
      //   href: "/coming-soon",
      //   external: false,
      //   isComingSoon: true,
      //   description: "test5Description",
      // },
    ],
  },
  {
    id: uuid(),
    isOpen: false,
    title: "Pricing",
    href: "#pricing",
    external: false,
  },
];
